### ISSUE TITLE
load command 0x80000034 is unknown

### ISSUE THREAD

**Issue by longma8520** [nodejs/node-addon-api#1165]
**Error:**
dlopen(/xxx/Contents/Resources/app.asar.unpacked/node_modules/xxx/adapter/xxx.node, 1): no suitable image found.  Did find:
	/xxx/Contents/Resources/app.asar.unpacked/node_modules/xxx/adapter/xxx.node: cannot load 'xxx.node' (load command 0x80000034 is unknown)
	/xxx/Contents/Resources/app.asar.unpacked/node_modules/xxx/adapter/xxx.node: cannot load 'xxx.node' (load command 0x80000034 is unknown)
Error: dlopen(/xxx/Contents/Resources/app.asar.unpacked/node_modules/xxx/adapter/xxx.node, 1): no suitable image found.  Did find:
	/xxx/Contents/Resources/app.asar.unpacked/node_modules/xxx/adapter/xxx.node: cannot load 'xxx.node' (load command 0x80000034 is unknown)
	/xxx/Contents/Resources/app.asar.unpacked/node_modules/xxx/adapter/xxx.node: cannot load 'xxx.node' (load command 0x80000034 is unknown)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)

node-addon-api version: 3.0.2
Only found in MacOS Mojave v10.14.6

**Comment by mhdawson** [comment]
I think we'd need more info/context and a more specific to be able to provide any help.

**Comment by mhdawson** [comment]
I'm going to close this since there was no response since the last request for more info. Please let us know if that was not the rigth thing to do.
