### ISSUE TITLE
Buffer.alloc is unavailable on Node 4

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#120]
```
Starting test suite

Running test 'arraybuffer'
Running test 'asyncworker'
Running test 'buffer'
Test failed: Internal Buffer
/home/nix/node/node-addon-api/test/testUtil.js:17
        throw e;
        ^

TypeError: Buffer.alloc is not a function
    at Array.<anonymous> (/home/nix/node/node-addon-api/test/buffer.js:17:28)
    at runGCTests (/home/nix/node/node-addon-api/test/testUtil.js:14:17)
    at Object.runGCTests (/home/nix/node/node-addon-api/test/testUtil.js:11:7)
    at test (/home/nix/node/node-addon-api/test/buffer.js:10:12)
    at Object.<anonymous> (/home/nix/node/node-addon-api/test/buffer.js:6:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
This is `npm test` on Node 4.

**Comment by mcollina** [comment]
You should use http://npm.im/safe-buffer

**Comment by gabrielschulhof** [comment]
@mcollina thanks!

**Comment by gabrielschulhof** [comment]
@mcollina actually, I can't use safe-buffer because we need the built-in buffer object, since we're testing the N-API bindings. So, I've wrapped the test in `if ('alloc' in Buffer) {...}`, meaning it will be skipped on Node 4, which makes sense.

**Comment by mcollina** [comment]
https://github.com/feross/safe-buffer/blob/master/index.js#L47 returns a built-in `Buffer`

**Comment by gabrielschulhof** [comment]
@mcollina the test uses N-API to instantiate a buffer and AFAICT safe-buffer cannot be used to augment an existing built-in Buffer after the fact.

**Comment by gabrielschulhof** [comment]
Hmmm ... the test works if I do `safeBuffer.Buffer.alloc(...)`. I'll do that.
