### ISSUE TITLE
New OSX testing - test failures

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#189]
We are in the process of adding OSX testing across different OSX versions from 10.08 to 10.13. See https://github.com/nodejs/build/issues/756.

We have this temporary job to run the tests on the new machines:

https://ci.nodejs.org/view/All/job/node-test-commit-osx-macstadium/

The tests seem to pass on 10.11 and 10.12  but we are seeing failures on 10.09 and 10.10  (we still need to work on getting the 10.08 and 10.13 machines configured)

This is a tracking issue for those failures so we can get help to investigate/resolve:

# Failures on 10.09

```
not ok 2065 sequential/test-inspector-port-zero
```

```
not ok 2065 sequential/test-inspector-port-zero
  ---
  duration_ms: 5.268
  severity: fail
  stack: |-
    assert.js:42
      throw new errors.AssertionError({
      ^
    
    AssertionError [ERR_ASSERTION]: exitCode: null, signal: SIGSEGV
        at ChildProcess.proc.on.mustCall (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/osx1009/test/sequential/test-inspector-port-zero.js:37:59)
        at ChildProcess.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/osx1009/test/common/index.js:522:15)
        at ChildProcess.emit (events.js:159:13)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
  ...
```

# Failures on 10.10

```
not ok 56 async-hooks/test-callback-error
not ok 109 async-hooks/test-callback-error
not ok 2065 sequential/test-inspector-port-zero
```

```
not ok 56 async-hooks/test-callback-error
  ---
  duration_ms: 15.480
  severity: fail
  stack: |-
    start case 1
    end case 1: 105.259ms
    start case 2
    end case 2: 100.860ms
    start case 3
    end case 3: 7.249ms
    Error: test_callback_abort
        at ActivityCollector.initHooks.oninit.common.mustCall (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/async-hooks/test-callback-error.js:27:45)
        at ActivityCollector.oninit (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/common/index.js:522:15)
        at ActivityCollector._init (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/async-hooks/init-hooks.js:185:10)
        at emitInitNative (internal/async_hooks.js:127:43)
        at emitInitScript (internal/async_hooks.js:294:3)
        at new AsyncResource (async_hooks.js:172:5)
        at Object.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/async-hooks/test-callback-error.js:29:5)
        at Module._compile (module.js:644:30)
        at Object.Module._extensions..js (module.js:655:10)
        at Module.load (module.js:563:32)
     1: node::Abort() [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     2: node::Chdir(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     4: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     5: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     6: 0x17fa153042fd
    
  ...
```
```
not ok 109 async-hooks/test-callback-error
  ---
  duration_ms: 15.549
  severity: fail
  stack: |-
    start case 1
    end case 1: 105.613ms
    start case 2
    end case 2: 103.350ms
    start case 3
    end case 3: 6.273ms
    Error: test_callback_abort
        at ActivityCollector.initHooks.oninit.common.mustCall (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/async-hooks/test-callback-error.js:27:45)
        at ActivityCollector.oninit (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/common/index.js:522:15)
        at ActivityCollector._init (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/async-hooks/init-hooks.js:185:10)
        at emitInitNative (internal/async_hooks.js:127:43)
        at emitInitScript (internal/async_hooks.js:294:3)
        at new AsyncResource (async_hooks.js:172:5)
        at Object.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/async-hooks/test-callback-error.js:29:5)
        at Module._compile (module.js:644:30)
        at Object.Module._extensions..js (module.js:655:10)
        at Module.load (module.js:563:32)
     1: node::Abort() [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     2: node::Chdir(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     4: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     5: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/out/Release/node]
     6: 0x28c0f81042fd
    
  ...
```
```
not ok 2065 sequential/test-inspector-port-zero
  ---
  duration_ms: 25.527
  severity: fail
  stack: |-
    assert.js:42
      throw new errors.AssertionError({
      ^
    
    AssertionError [ERR_ASSERTION]: exitCode: null, signal: SIGSEGV
        at ChildProcess.proc.on.mustCall (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/sequential/test-inspector-port-zero.js:37:59)
        at ChildProcess.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx-macstadium/nodes/macstadium-osx1010/test/common/index.js:522:15)
        at ChildProcess.emit (events.js:159:13)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
  ...
```

**Comment by mhdawson** [comment]
Failures may be related to https://github.com/nodejs/build/issues/773

**Comment by mhdawson** [comment]
2 extra failures on 10.10 seem to be resolved by solution in https://github.com/nodejs/build/issues/.  But still see failure of `not ok 2065 sequential/test-inspector-port-zero` on both 10.09 and 10.10

**Comment by mhdawson** [comment]
Got the wrong repo, going to close and open issue in node core repo

**Comment by mhdawson** [comment]
Proper issue: https://github.com/nodejs/node/issues/17164
