### ISSUE TITLE
node-addon-api test failures on linuxOne and AIX

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#230]
After I landed this on Friday https://github.com/nodejs/node-addon-api/commit/9c4d321b57327de69e1f95bff06256174f001153.  There have been failures in the nightly runs across platforms.

I'm seeing faliures on AIX and linuxOne.  Likely and issue with endianess as they are both big endian.

https://ci.nodejs.org/job/node-test-node-addon-api/MACHINE=rhel72-s390x/207/console

```
> node-addon-api@1.2.0 test /data/iojs/build/workspace/node-test-node-addon-api/MACHINE/rhel72-s390x/node-addon-api
> node test

Starting test suite

Running test 'arraybuffer'
Running test 'asyncworker'
Running test 'basic_types/number'
Running test 'basic_types/value'
Running test 'buffer'
Running test 'dataview/dataview'
Running test 'dataview/dataview_read_write'
assert.js:74
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 4.170874845499384e-8 strictEqual 10.199999809265137
    at testReadData (/data/iojs/build/workspace/node-test-node-addon-api/MACHINE/rhel72-s390x/node-addon-api/test/dataview/dataview_read_write.js:35:12)
    at test (/data/iojs/build/workspace/node-test-node-addon-api/MACHINE/rhel72-s390x/node-addon-api/test/dataview/dataview_read_write.js:60:3)
    at Object.<anonymous> (/data/iojs/build/workspace/node-test-node-addon-api/MACHINE/rhel72-s390x/node-addon-api/test/dataview/dataview_read_write.js:6:1)
    at Module._compile (module.js:666:30)
    at Object.Module._extensions..js (module.js:677:10)
```

@jbarz, @romandev  can you take a look.

**Comment by romandev** [comment]
I'll investigate this issue.
