### ISSUE TITLE
Exceptions thrown in Init don't make it to JavaScript

### ISSUE THREAD

**Issue by fluggo** [nodejs/node-addon-api#239]
I suspect the problem is with the underlying NAPI than this project, because when I trace the code, it looks like node-addon-api does everything it's supposed to do. But this is the API where I found the problem, so I'm reporting it here.

test.cpp:

```cpp
#include "napi.h"
#include <stdexcept>
#include <iostream>

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  try {
    throw Napi::Error::New(env, "Test");
    return exports;
  }
  catch(const Napi::Error& e) {
    std::cout << "Caught NAPI exception\n";
    throw;
  }
  catch(const std::exception& e) {
    std::cout << "Caught std exception\n";
    throw;
  }
  catch(...) {
    std::cout << "Caught exception\n";
    throw;
  }
}

NODE_API_MODULE(test, Init)
```

binding.gyp:

```python
{
  "targets": [
    {
      "target_name": "test",
      "sources": ["test.cpp"],
      "cflags!": ["-fno-exceptions"],
      "cflags": ["-std=c++11"],
      "cflags_cc!": ["-fno-exceptions"],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      "dependencies": [
        "<!(node -p \"require('node-addon-api').gyp\")"
      ]
    }
  ]
}
```

index.js:

```javascript
const test = require('./build/Debug/test.node');
console.log('No exception thrown');
```

Output:

```
~/software/napi-init-exception-test $ node -v
v8.9.4
~/software/napi-init-exception-test $ node index.js
Caught NAPI exception
No exception thrown
(node:1243) Warning: N-API is an experimental feature and could change at any time.
```

**Comment by fluggo** [comment]
It looks like this may be a bug in NAPI itself. Running a modified version of [NAPI's hello world](https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/1_hello_world/napi) which throws an exception after adding the `hello` method to `exports`, the exception gets reported on the `hello()` call:

```
/app/pure-napi/hello.js:3
console.log(addon.hello()); // 'world'
                  ^

Error [CODE]: Test error
    at Object.Module._extensions..node (module.js:678:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at bindings (/app/pure-napi/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/app/pure-napi/hello.js:1:94)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
```

Removing the call to hello causes no exception to be reported at all. Doing the same with node-addon-api produces the same behavior.

**Comment by mhdawson** [comment]
Any chance you've confirmed it has the correct behaviour with a non n-api addon ?

**Comment by fluggo** [comment]
Verified, it does work when not using N-API. In a pure V8-only addon:

```cpp
void Init(Handle<Object> exports) {
  Isolate* isolate = Isolate::GetCurrent();
  exports->Set(String::NewFromUtf8(isolate, "hello"),
      FunctionTemplate::New(isolate, Method)->GetFunction());
  isolate->ThrowException(String::NewFromUtf8(isolate, "Test error"));
}
```

I get:

```
root@a5d5c8becf83:/app/pure-node# node hello.js

module.js:678
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Test error
```

**Comment by fluggo** [comment]
Also, I did put this on the [main node tracker](nodejs/node#19437).

**Comment by mhdawson** [comment]
@fluggo thanks for validating, will help narrow down where to start looking.

**Comment by mhdawson** [comment]
Believe this was fixed in https://github.com/nodejs/node/issues/19437. Please re-open if that is not the case.  @fluggo thanks for reporting.
