### ISSUE TITLE
node-addon-api test broken on 6.x 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#296]
Seems the tests were broken on 6.x when I landed https://github.com/nodejs/node-addon-api/commit/4b8918b3524bb8498dbac7811faf3e3c759d2054.

It is just the test, not an ABI breakage:

```
Starting test suite

Running test 'arraybuffer'
Running test 'asyncworker'
module.js:478
    throw err;
    ^

Error: Cannot find module 'async_hooks'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mhdawson/newpull/node-addon-api/test/asyncworker.js:4:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
npm ERR! Test failed.  See above for more details.

```

**Comment by mhdawson** [comment]
Working on fix.
