### ISSUE TITLE
Addon built with node 6.9.0 fails on ABI version check in node 8 and 10

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#310]
The addon built with node 6.9.0, fails to load into node 8 and 10, because of the ABI version check.

When built with with node 6.14.3, no error happens.

Steps to reproduce using [async_pi_estimate example](https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/async_pi_estimate/node-addon-api) given below.

Following this [comment](https://github.com/nodejs/node-addon-api/issues/291#issuecomment-401380610), is node 6.9.0 the earliest version to use for building node 6, 8 and 10 compatible addons?

```shell

$ pwd
/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api

###
### build with 6.9.0
###

$ nvm use 6.9.0
Now using node v6.9.0 (npm v6.2.0)

[py2714] www-admin@978fe603d289 ~/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api (master)
$ npm i

> async_work@0.0.0 install /home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api
> node-gyp rebuild

make: Entering directory '/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/build'
  CXX(target) Release/obj.target/node-api/node_modules/node-addon-api/src/node_api.o
  CXX(target) Release/obj.target/node-api/node_modules/node-addon-api/src/node_internals.o
  AR(target) Release/obj.target/node_modules/node-addon-api/src/node-api.a
  COPY Release/node-api.a
  CXX(target) Release/obj.target/addon/addon.o
  CXX(target) Release/obj.target/addon/pi_est.o
  CXX(target) Release/obj.target/addon/sync.o
  CXX(target) Release/obj.target/addon/async.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
make: Leaving directory '/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/build'
audited 2 packages in 4.226s
found 0 vulnerabilities


[py2714] www-admin@978fe603d289 ~/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api (master)
$ node addon
Sync method:
	π ≈ 3.14157864 (0.000014013589793027137 away from actual)
	Took 890ms

Async method:
	π ≈ 3.14190464 (0.0003119864102067993 away from actual)
	Took 273ms

###
### fails with node 8
###

$ nvm use 8
Now using node v8.11.3 (npm v6.2.0)

[py2714] www-admin@978fe603d289 ~/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api (master)
$ node addon
/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/build/Release/addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/addon.js:1:94)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

$ npm ls --depth 0
+-- bindings@1.3.0
`-- node-addon-api@1.4.0

###
### build with 6.14.3
###

$ nvm use 6.14.3
Now using node v6.14.3 (npm v6.2.0)

[py2714] www-admin@978fe603d289 ~/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api (master)
$ npm i

> async_work@0.0.0 install /home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api
> node-gyp rebuild

make: Entering directory '/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/build'
  SOLINK_MODULE(target) Release/obj.target/node_modules/node-addon-api/src/nothing.node
  COPY Release/nothing.node
  CXX(target) Release/obj.target/addon/addon.o
  CXX(target) Release/obj.target/addon/pi_est.o
  CXX(target) Release/obj.target/addon/sync.o
  CXX(target) Release/obj.target/addon/async.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
make: Leaving directory '/home/www-admin/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api/build'
audited 2 packages in 3.269s
found 0 vulnerabilities

###
### works in node 8
###

$ nvm use 8
Now using node v8.11.3 (npm v6.2.0)

[py2714] www-admin@978fe603d289 ~/src/abi-stable-node-addon-examples/async_pi_estimate/node-addon-api (master)
$ node addon
Sync method:
	π ≈ 3.14157864 (0.000014013589793027137 away from actual)
	Took 899ms

(node:19288) Warning: N-API is an experimental feature and could change at any time.
Async method:
	π ≈ 3.14190464 (0.0003119864102067993 away from actual)
	Took 284ms

```

**Comment by gabrielschulhof** [comment]
@bsrdjan 6.14.2 was the first version of Node.js 6.x to ship with N-API. Thus, if you build on earlier versions, node-addon-api will create a normal addon and will link the addon statically to its own, internal copy of N-API, which it builds along with the addon.

Since it's a normal addon, it is subject to the same requirements as other normal addons – namely, that its ABI version match.

If you build your addon with node-addon-api on a version of Node.js that does not have N-API, then you get the benefit of having a codebase that is N-API-ready, but you do not get the benefit of binaries which work on all versions of Node.js which ship with N-API.

So, to have the addon work on all versions of Node.js which ship with N-API, you should build it on at least Node.js v6.14.2.

**Comment by bsrdjan** [comment]
Thanks a lot for the clarification.
