### ISSUE TITLE
Send C++ class to node with ObjectWrap without data loss

### ISSUE THREAD

**Issue by sziraqui** [nodejs/node-addon-api#500]
I am trying to pass cv::Mat from c++ to node and vice versa using node-addon-api. I wrote lightweight wrapper for cv::Mat but there seems to be no way to convert this `ObjectWrap`ed class into Object from within C++ that will allow sending it to node. I have viewed issue #96 but the methods discussed did not help. I saw [this](https://github.com/nodejs/abi-stable-node-addon-examples/blob/master/8_passing_wrapped/node-addon-api/addon.cc#L7) example but this method is sending something received from JS back to JS and not created in C++ side. Here is my code to reproduce my problem:

The wrapper class:
```
Napi::FunctionReference Nodoface::Image::constructor;

Napi::Object Nodoface::Image::Init(Napi::Env env, Napi::Object exports) {
    Napi::HandleScope scope(env);
    Napi::Function func = DefineClass(env, "Image", {
        InstanceMethod("shape", &Nodoface::Image::Shape),
        InstanceMethod("type", &Nodoface::Image::Type)
    });
    constructor = Napi::Persistent(func);
    constructor.SuppressDestruct();
    exports.Set("Image", func);
    return exports;
}

Nodoface::Image::Image(const Napi::CallbackInfo& info) : ObjectWrap<Nodoface::Image>(info) {
    std::cout<<"inside Mat constructor\n";
    if(info.Length() == 2) {
        std::cout<<"Mat Unwrap start\n";
        Image * img = Napi::ObjectWrap<Image>::Unwrap(info[1].As<Napi::Object>());
        std::cout<<"Mat Unwrap end\n";
        this->mat = img->mat;
    }
    std::cout<<"Mat constructor finish\n";
}

Nodoface::Image Nodoface::Image::New(const Napi::CallbackInfo& info, cv::Mat& mat) {
    auto env = info.Env();
    std::cout<<"inside Mat New\n";
    Nodoface::Image img(info);
    img.mat = &mat;
    return img;
}
//..
```

Functions that pass the wrapper class to node:
```
Napi::Value Nodoface::readImage(const Napi::CallbackInfo &info) {
    std::string path = info[0].As<Napi::String>().Utf8Value();
    cv::Mat mat = cv::imread(path, cv::IMREAD_UNCHANGED);
    auto img = Nodoface::Image::New(info, mat);
    Napi::Value val = img.Value(); // returns the whole addon!! instead of wrapped object
    return val;
}

Napi::Value Nodoface::showImage(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    Nodoface::Image image(info);
    cv::Mat mat = image.GetMat();
    std::string title = info.Length() >= 2? info[1].As<Napi::String>().Utf8Value() : "output";
    int ms = info.Length() >=3 ? info[2].As<Napi::Number>().Int32Value() : 0;
    cv::namedWindow(title, cv::WINDOW_AUTOSIZE);
    cv::imshow(title, mat);
    cv::waitKey(ms);
    return env.Null();
}
```
Usage in nodejs:
```
const nodoface = require('../api/nodoface');
let argv = process.argv.slice(2);
console.log(argv);
let img = nodoface.readImage(argv[0]);
console.log('image', img);
nodoface.showImage(img);
```
The error:
```
[ '/home/sziraqui/MyLibs/OpenFace/samples/image_sequence/001.jpg' ]
inside Mat New
inside Mat constructor
Mat constructor finish
image { ImageCapture: [Function: ImageCapture],
  SequenceCapture: [Function: SequenceCapture],
  Image: [Function: Image],
  showImage: [Function],
  readImage: [Function] }
/home/sziraqui/Projects/nodoface/examples/cv_input_output.js:6
nodoface.showImage(img);
         ^

Error: Invalid argument
    at Object.<anonymous> (/home/sziraqui/Projects/nodoface/examples/cv_input_output.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Invalid Argument because what I am receiving from C++ side is the addon object instead of wrapper Image object. Clearly ObjectWrap is not being converted to Object.

**Comment by kevinGodell** [comment]
Shouldn't readImage() and showImage() be registered as instance methods inside of DefineClass?

**Comment by sziraqui** [comment]
They are exported as functions. Nodoface is just a namespace. Havent included them for brevity. You can see the whole source code [here](https://github.com/sziraqui/nodoface/blob/master/src/io/OutputUtils.cpp)

**Comment by sziraqui** [comment]
I followed this example and I was able to implement the wrapper class correctly. Here is the updated code:
wrapper class
```
Napi::FunctionReference Nodoface::Image::constructor;
// static methods
Napi::Object Nodoface::Image::Init(Napi::Env env, Napi::Object exports) {
    Napi::HandleScope scope(env);
    Napi::Function func = DefineClass(env, "Image", {
       //.. instance methods
    });
    constructor = Napi::Persistent(func);
    constructor.SuppressDestruct();
    exports.Set("Image", func);
    return exports;
}

Napi::Object Nodoface::Image::NewObject(Napi::Env env, cv::Mat& mat) {
    // Get continuous mat data
    uchar* data;
    size_t length = mat.total() * mat.channels();
    if (mat.isContinuous()) {
        std::cout<<"NewObject mat is continuous\n";
        data = mat.data;
    } else {
        std::cout<<"NewObject mat not continuous\n";
        cv::Mat flatView = mat.reshape(1, length);
        std::vector<uchar> vec = flatView.clone(); // Is clone redundant?
        data = vec.data();
    }
    // Create ArrayBuffer from data
    Napi::ArrayBuffer ab = Napi::ArrayBuffer::New(env, data, sizeof(uchar)*length);
    Napi::TypedArrayOf<uchar> arr = Napi::TypedArrayOf<uchar>::New(env, length, ab, 0); // arg0
    // Create array for mat dimensions
    std::vector<int> sizeVec(mat.size.dims());
    for(int i = 0; i < mat.size.dims(); ++i) {
        sizeVec[i] = mat.size[i];
    }
    Napi::ArrayBuffer sizeBuf = Napi::ArrayBuffer::New(env, sizeVec.data(), sizeof(int)*sizeVec.size());
    Napi::TypedArrayOf<int> size = Napi::TypedArrayOf<int>::New(env, sizeVec.size(), sizeBuf, 0); // arg1
    // Create mat type Number
    Napi::Number type = Napi::Number::New(env, mat.type());  // arg2
    Napi::Object imageObj = Image::constructor.New({ arr, size, type });
    return imageObj;
}
// cpp only
cv::Mat Nodoface::Image::NewMat(Napi::TypedArrayOf<uchar> &arr, Napi::TypedArrayOf<int> &size, Napi::Number &type) {
    std::cout<<"newMat called\n";
    // Get mat data
    auto buf = arr.ArrayBuffer();
    uchar* data = reinterpret_cast<uchar *>(buf.Data()); // reinterpret_cast for void* to uchar*
    // Get mat size
    auto sizeBuf = size.ArrayBuffer();
    const int* matSize = reinterpret_cast<int *>(sizeBuf.Data());
    // Get Mat type
    int matType = type.Int32Value();
    // Create mat
    cv::Mat mat(matSize[0], matSize[1], matType, data);
    std::cout<<"NewMat mat restored\n";
    return mat;
}

// constructor
Nodoface::Image::Image(const Napi::CallbackInfo& info) : ObjectWrap<Nodoface::Image>(info) {
    std::cout<<"inside Mat constructor\n";
    int len = info.Length();
    std::cout<<"info.Length " << len<<std::endl;
    auto env = info.Env();
   
    if (len == 1 && info[0].IsObject()) {
        // copy constructor
        std::cout<<"Mat Unwrap start\n";
        Image * img = Napi::ObjectWrap<Image>::Unwrap(info[1].As<Napi::Object>());
        std::cout<<"Mat Unwrap end\n";
        this->mat = img->mat;
    } else if (len == 3) {
        //.. type checking truncated for brevity
        auto arr = info[0].As<Napi::TypedArrayOf<uchar>>();
        auto size = info[1].As<Napi::Int32Array>();
        auto type = info[2].As<Napi::Number>();
        this->mat = Image::NewMat(arr, size, type);
    }
}

// cpp only
cv::Mat Nodoface::Image::GetMat() {
    return this->mat;
}
```
Wrappers for imread and imshow:
```
Napi::Object Nodoface::Init(Napi::Env env, Napi::Object exports) {
    exports.Set("showImage", Napi::Function::New(env, Nodoface::showImage));
    exports.Set("readImage", Napi::Function::New(env, Nodoface::readImage));
    return exports;
}

// js-args: output of readImage (Napi::Object of Image class)
Napi::Value Nodoface::showImage(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    // Unwrap Image and get mat
    Napi::Object parent = info[0].As<Napi::Object>();
    Nodoface::Image *image = Napi::ObjectWrap<Nodoface::Image>::Unwrap(parent);
    cv::Mat mat = image->GetMat();
    std::cout<<"showImage: mat rows :"<<mat.rows <<" cols:"<<mat.cols << " type :" <<mat.type()<<std::endl;
    // Get optional arguments
    std::string title = info.Length() >= 2? info[1].As<Napi::String>().Utf8Value() : "output";
    int ms = info.Length() >=3 ? info[2].As<Napi::Number>().Int32Value() : 0;
    // Display mat
    cv::namedWindow(title, cv::WINDOW_AUTOSIZE);
    std::cout<<"showImage imshow\n";
    cv::imshow(title, mat);
    std::cout<<"showImage imshow done\n";
    cv::waitKey(ms);
    return env.Undefined();
}

Napi::Value Nodoface::readImage(const Napi::CallbackInfo &info) {
    std::string path = info[0].As<Napi::String>().Utf8Value();
    std::cout<<"image path:" << path << std::endl;
    cv::Mat mat = cv::imread(path, cv::IMREAD_UNCHANGED);
    std::cout<<"readImage: mat rows :"<<mat.rows <<" cols:"<<mat.cols << " type :" <<mat.type()<<std::endl;
    auto imgObj = Nodoface::Image::NewObject(info.Env(), mat);
    return imgObj;
}
```
The code works. But only the unwrapped Image class does not retain the mat data. The Mat retains its dimensions (mat.rows and mat.cols) as well as mat.type()  but not the large pixel data. It looks like just garbage values are stored in the mat. How do I ensure the Unwrapped object retains all the data? I tried using Napi::External<uchar> to store the pointer to mat data but it did not make any difference.

**Comment by mhdawson** [comment]
It sounds like potentially one of 2 problems (without having looked through the code too much):

1) if you are storing a pointer to the image data in Mat you need to makes that what it points to stays in scope (ie not stack allocated)

2) if you are storing a reference to a JavaScript object that contains the data (which I think may be the case since you were talking about nested wrapped objects) then you need to make sure it will be kept alive through a Napi::Reference where refcount != 0.  You would then decrement the reference count when the object that is holding the reference is destructed.

If it's case 2) using an External would not help as you need something referencing the External to keep it alive./

**Comment by sziraqui** [comment]
Its case 1. I am creating ArrayBuffer from a pointer to Mat data and then a TypedArrayOf<uchar> using the ArrayBuffer. I made some progress since I posted this issue. I was not creating the ArrayBuffer correctly. Now I can create the Napi::Object instance and send it to node. But sending this same instance from node to C++ is destroying some data. Few topmost pixels are not retained. Returning the wrapper's Object with EscapableHandleScope::Escape is also not making any difference.

**Comment by sziraqui** [comment]
Here's the modified partially working NewObject method:
```
Napi::Value Nodoface::Image::NewObject(Napi::Env env, cv::Mat& mat) {
    Napi::EscapableHandleScope scope(env);
    // Get continuous mat data
    uchar* data;
    size_t length = mat.total() * mat.channels();
    mat = mat.clone(); // ensures mat is continuous and also prevents segfault
    data = mat.data;
    // Create ArrayBuffer from data
    Napi::ArrayBuffer ab = Napi::ArrayBuffer::New(env, data, sizeof(uchar)*length);
    Napi::TypedArrayOf<uchar> arr = Napi::TypedArrayOf<uchar>::New(env, length, ab, 0); // arg0
    // Create array for mat dimensions
    std::vector<int> sizeVec(mat.size.dims());
    for(int i = 0; i < mat.size.dims(); ++i) {
        sizeVec[i] = mat.size[i];
    }
    Napi::ArrayBuffer sizeBuf = Napi::ArrayBuffer::New(env, sizeVec.data(), sizeof(int)*sizeVec.size());
    Napi::TypedArrayOf<int> size = Napi::TypedArrayOf<int>::New(env, sizeVec.size(), sizeBuf, 0); // arg1
    // Create mat type Number
    Napi::Number type = Napi::Number::New(env, mat.type());  // arg2
    Napi::Object imageObj = Image::constructor.New({ arr, size, type });
    return scope.Escape(imageObj);
}
```

**Comment by sziraqui** [comment]
NewObject() is called to create Napi::Object from cv::Mat. If I unwrap this object from within cpp, all data is intact but when it is passed to node side, I see loss of data those were set using pointer to array.

**Comment by sziraqui** [comment]
I ran my program on several images. Sometimes the image is corrupt sometimes it is not. So the issue now boils down to preventing data loss when passing data from cpp to node and back to cpp. The pointer to Mat data is the problem. The pointer was copied from a local instance of Mat. When the function returns, the local instance is probably lost. By the time I call showImage() from node, the memory location may or may not have the original data. Can someone help me with this issue?

**Comment by sziraqui** [comment]
The problem is fixed! Mat object returned from cv::imread() was allocated on stack. In NewObject() method I ensure cv::Mat is heap allocated using `new`. Now there is no loss in data.
@mhdawson Thank you very much! 
Now I have one last question. Is there any callback called when any ObjectWrapper instance is deleted by the program? I need to delete[] the Mat data when its holding wrapper object is destructed.

**Comment by mhdawson** [comment]
@sziraqui you should just be able to implement a destructor in the class that extends ObjectWrap.  It should be called at some point after the JS Object associated with the instance goes out of scope (no guarantee on how soon after though, its up to the gc)

**Comment by sziraqui** [comment]
Alright! I will do that. Thanks! Closing this now.
