### ISSUE TITLE
Trying to extend AsyncWorker, getting `undefined symbol` when module is loaded.

### ISSUE THREAD

**Issue by markdirish** [nodejs/node-addon-api#521]
I have a database connector that has about 12 AsyncWorker classes that all have different `Execute`s and `OnOk`s, but have identical `OnError`s. I decided to create a class called `ODBCAsyncWorker` to encapsulate all of the error logic in one place to adhere to DRY principles. My module compiles fine, but at load time I am getting the following error:

```
[mirish@oc6133424434 node-odbc]$ node ../test/app.js
internal/modules/cjs/loader.js:805
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/mirish/odbc/node-odbc/build/Release/odbc.node: undefined symbol: _ZTV15ODBCAsyncWorker
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mirish/odbc/node-odbc/lib/odbc.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

The code for my `ODBCAsyncWorker` class looks like:

*odbc.h*:
```c++
class ODBCAsyncWorker : public Napi::AsyncWorker {

  public:
    // static Napi::Value Init(Napi::Env env, Napi::Object exports);
    ODBCAsyncWorker(Napi::Function& callback);
    ~ODBCAsyncWorker();

  protected:
    ODBCError *errors;
    unsigned int errorCount;

    bool CheckAndHandleErrors(SQLRETURN returnCode, SQLSMALLINT handleType, SQLHANDLE handle, const char *message);
    ODBCError* GetODBCErrors(SQLSMALLINT handleType, SQLHANDLE handle);
    void OnError(const Napi::Error &e);
};
```
*odbc.cpp*:
```c++
ODBCAsyncWorker::ODBCAsyncWorker(Napi::Function& callback) : Napi::AsyncWorker(callback) {};

// TODO: Documentation for this function
void ODBCAsyncWorker::OnError(const Napi::Error &e) {

  Napi::Env env = Env();
  Napi::HandleScope scope(env);

  // add the additional information to the Error object
  Napi::Error error = Napi::Error::New(env, e.Message());
  Napi::Array odbcErrors = Napi::Array::New(env);

  for (unsigned int i = 0; i < errorCount; i++) {
    ODBCError odbcError = errors[i];
    Napi::Object errorObject = Napi::Object::New(env);

    errorObject.Set(
      Napi::String::New(env, "state"),
      Napi::String::New(env, (const char*)odbcError.state)
    );
    errorObject.Set(
      Napi::String::New(env, "code"),
      Napi::Number::New(env, odbcError.code)
    );
    errorObject.Set(
      Napi::String::New(env, "message"),
      Napi::String::New(env, (const char*)odbcError.message)
    );

    odbcErrors.Set(i, errorObject);
  }

  error.Set(
    Napi::String::New(env, "odbcErrors"),
    odbcErrors
  );

  std::vector<napi_value> callbackArguments;
  callbackArguments.push_back(error.Value());

  Callback().Call(callbackArguments);
}

// TODO: Documentation for this function
ODBCError* ODBCAsyncWorker::GetODBCErrors(SQLSMALLINT handleType, SQLHANDLE handle) {
  // function body
}

// TODO: Documentation for this function
bool ODBCAsyncWorker::CheckAndHandleErrors(SQLRETURN returnCode, SQLSMALLINT handleType, SQLHANDLE handle, const char *message) {
  // function body
}
```
And then all my sub AsyncWorkers further extend ODBCAsyncWorker and add the appropriate `Execute` and `OnOk` funcctions

I have tried to add an `Init` function and run it through `InitAll`, but my ODBCAsyncWorker doesn't really have anything to initialize, and anyways it didn't fix the error. Do I need to somehow do an ObjectWrap or something similar?

Clearly just a some misunderstanding I have, but I hope someone can quickly point out where I'm going wrong.

**Comment by markdirish** [comment]
I declared but didn't define the destructor... and since it had the same name as the class itself, it looked in the error that the class wasn't found. Closing my issue!
