### ISSUE TITLE
Building node-addon-api project fails to link to n-api C code.

### ISSUE THREAD

**Issue by jonathansensus** [nodejs/node-addon-api#593]
For my work I am porting a NAN library to n-api with node-addon-api.
I am newish to C++ programing and native addons for node, so please bear with me.

The compiler is able to create object files out of all of my code, but when it tries to link the n-api C code of errors like: ```undefined reference to `napi_create_function'``` or ```undefined reference to `napi_create_string_utf8'```. It seems like it has no access to the node_api.h.
Below is my bindings.gyp file.

As a note, I did use the migration script referenced [here](https://github.com/nodejs/node-addon-api/tree/master/tools).

``` python
{
  'targets': [
    {
      'target_name': 'xmljs',
      'cflags!': [ '-fno-exceptions' ],
      'cflags_cc!': [ '-fno-exceptions' ],
      'xcode_settings': { 'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
        'CLANG_CXX_LIBRARY': 'libc++',
        'MACOSX_DEPLOYMENT_TARGET': '10.7',
      },
      'msvs_settings': {
        'VCCLCompilerTool': { 'ExceptionHandling': 1 },
      },
      'product_extension': 'node',
      # 'type': 'shared_library',
      'include_dirs': [
        '<!@(node -p "require(\'node-addon-api\').include")',
        # other libs
      ],
      'ldflags': [
        "-Wl,-z,defs"
      ],
      'cflags': [ '-Wall' ],
      'xcode_settings': {
        'OTHER_CFLAGS': [ '-Wall' ]
      },
      'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"],
      'sources': [
        # source code
      ],
      'defines': [
        'IN_LIBXMLJS',
        '_REENTRANT',
      ],
      'conditions': [
        ['OS=="mac"', {
          # node-gyp 2.x doesn't add this anymore
          # https://github.com/TooTallNate/node-gyp/pull/612
          'xcode_settings': {
            'CLANG_CXX_LANGUAGE_STANDARD': 'c++11',
            'OTHER_LDFLAGS': [
              '-undefined dynamic_lookup'
            ],
          },
        }],
        ['OS=="win"', {
          'defines': [
            'HAVE_WIN32_THREADS',
          ],
        }, {
          'defines': [
            'HAVE_LIBPTHREAD',
            'HAVE_PTHREAD_H',
            'HAVE_UNISTD_H',
            'HAVE_RAND_R',
          ],
        }],
      ]
    }
  ]
}
```
What do you think would be causing this?
Thanks in advance!

**Comment by NickNaso** [comment]
Hi @jonathansensus,
which version of Node.js are you using? Is your code public?

**Comment by jonathansensus** [comment]
I am using node 10.16.0 currently and the code is not public right now sadly.

**Comment by NickNaso** [comment]
The `binding.gyp` seems good. 

```cpp
#include <napi.h>

Napi::String Method(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  return Napi::String::New(env, "world");
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "hello"),
              Napi::Function::New(env, Method));
  return exports;
}

NODE_API_MODULE(xmljs, Init)
```
Could you  create a file and insert  code above and  in `sources` section insert only the file that file and try to build the add-on?

**Comment by jonathansensus** [comment]
Thanks for the response btw.

I made ```test.cc``` containing your code and added it to the sources list. I have the same problem.

node-gyp build output:
```
make: Entering directory '/home/jstefani/Documents/github/libxmljs/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/xmljs/test.o
  SOLINK_MODULE(target) Release/obj.target/xmljs.node
Release/obj.target/xmljs/test.o: In function `Init(Napi::Env, Napi::Object)':
test.cc:(.text+0x8b): undefined reference to `napi_create_function'
test.cc:(.text+0xe4): undefined reference to `napi_create_symbol'
test.cc:(.text+0x103): undefined reference to `napi_create_external'
test.cc:(.text+0x14f): undefined reference to `napi_define_properties'
test.cc:(.text+0x17c): undefined reference to `napi_create_string_utf8'
test.cc:(.text+0x192): undefined reference to `napi_set_property'
Release/obj.target/xmljs/test.o: In function `Method(Napi::CallbackInfo const&)':
test.cc:(.text+0x2a2): undefined reference to `napi_create_string_utf8'
Release/obj.target/xmljs/test.o: In function `Napi::Error::~Error()':
test.cc:(.text._ZN4Napi5ErrorD2Ev[_ZN4Napi5ErrorD5Ev]+0x5b): undefined reference to `napi_delete_reference'
Release/obj.target/xmljs/test.o: In function `Napi::AsyncContext::~AsyncContext()':
test.cc:(.text._ZN4Napi12AsyncContextD2Ev[_ZN4Napi12AsyncContextD5Ev]+0x21): undefined reference to `napi_async_destroy'
Release/obj.target/xmljs/test.o: In function `Napi::AsyncContext::~AsyncContext()':
test.cc:(.text._ZN4Napi12AsyncContextD0Ev[_ZN4Napi12AsyncContextD5Ev]+0x28): undefined reference to `napi_async_destroy'
Release/obj.target/xmljs/test.o: In function `Napi::CallbackScope::~CallbackScope()':
test.cc:(.text._ZN4Napi13CallbackScopeD2Ev[_ZN4Napi13CallbackScopeD5Ev]+0x1c): undefined reference to `napi_close_callback_scope'
Release/obj.target/xmljs/test.o: In function `Napi::CallbackScope::~CallbackScope()':
test.cc:(.text._ZN4Napi13CallbackScopeD0Ev[_ZN4Napi13CallbackScopeD5Ev]+0x23): undefined reference to `napi_close_callback_scope'
Release/obj.target/xmljs/test.o: In function `Napi::Error::~Error()':
test.cc:(.text._ZN4Napi5ErrorD0Ev[_ZN4Napi5ErrorD5Ev]+0x65): undefined reference to `napi_delete_reference'
Release/obj.target/xmljs/test.o: In function `Napi::Error::Fatal(char const*, char const*)':
test.cc:(.text._ZN4Napi5Error5FatalEPKcS2_[_ZN4Napi5Error5FatalEPKcS2_]+0x12): undefined reference to `napi_fatal_error'
Release/obj.target/xmljs/test.o: In function `Napi::Error::New(napi_env__*)':
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x32): undefined reference to `napi_get_last_error_info'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x65): undefined reference to `napi_is_exception_pending'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x91): undefined reference to `napi_create_string_utf8'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0xc7): undefined reference to `napi_create_error'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x11b): undefined reference to `napi_create_reference'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x150): undefined reference to `napi_get_and_clear_last_exception'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x178): undefined reference to `napi_get_and_clear_last_exception'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x19a): undefined reference to `napi_create_type_error'
test.cc:(.text._ZN4Napi5Error3NewEP10napi_env__[_ZN4Napi5Error3NewEP10napi_env__]+0x234): undefined reference to `napi_delete_reference'
Release/obj.target/xmljs/test.o: In function `Napi::Error::what() const':
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0x42): undefined reference to `napi_open_escapable_handle_scope'
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0x67): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0x8a): undefined reference to `napi_get_named_property'
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0xa7): undefined reference to `napi_escape_handle'
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0xc3): undefined reference to `napi_close_escapable_handle_scope'
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0xd6): undefined reference to `napi_get_value_string_utf8'
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0x13a): undefined reference to `napi_get_value_string_utf8'
test.cc:(.text._ZNK4Napi5Error4whatEv[_ZNK4Napi5Error4whatEv]+0x339): undefined reference to `napi_close_escapable_handle_scope'
Release/obj.target/xmljs/test.o: In function `Napi::AsyncWorker::OnError(Napi::Error const&)':
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0x46): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0x6f): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0x8d): undefined reference to `napi_open_escapable_handle_scope'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0xb2): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0xda): undefined reference to `napi_call_function'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0xf3): undefined reference to `napi_is_exception_pending'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0x10b): undefined reference to `napi_escape_handle'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0x120): undefined reference to `napi_close_escapable_handle_scope'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0x188): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE[_ZN4Napi11AsyncWorker7OnErrorERKNS_5ErrorE]+0x1d3): undefined reference to `napi_close_escapable_handle_scope'
Release/obj.target/xmljs/test.o: In function `Napi::AsyncWorker::OnOK()':
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0x68): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0x85): undefined reference to `napi_open_escapable_handle_scope'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0xaa): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0xd8): undefined reference to `napi_call_function'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0xf1): undefined reference to `napi_is_exception_pending'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0x109): undefined reference to `napi_escape_handle'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0x11e): undefined reference to `napi_close_escapable_handle_scope'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0x178): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZN4Napi11AsyncWorker4OnOKEv[_ZN4Napi11AsyncWorker4OnOKEv]+0x1da): undefined reference to `napi_close_escapable_handle_scope'
Release/obj.target/xmljs/test.o: In function `Napi::Error::ThrowAsJavaScriptException() const':
test.cc:(.text._ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv[_ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv]+0x2a): undefined reference to `napi_open_handle_scope'
test.cc:(.text._ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv[_ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv]+0x48): undefined reference to `napi_get_reference_value'
test.cc:(.text._ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv[_ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv]+0x59): undefined reference to `napi_throw'
test.cc:(.text._ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv[_ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv]+0x6e): undefined reference to `napi_close_handle_scope'
test.cc:(.text._ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv[_ZNK4Napi5Error26ThrowAsJavaScriptExceptionEv]+0xc5): undefined reference to `napi_close_handle_scope'
Release/obj.target/xmljs/test.o: In function `Napi::details::CallbackData<Napi::String (*)(Napi::CallbackInfo const&), Napi::String>::Wrapper(napi_env__*, napi_callback_info__*)':
test.cc:(.text._ZN4Napi7details12CallbackDataIPFNS_6StringERKNS_12CallbackInfoEES2_E7WrapperEP10napi_env__P20napi_callback_info__[_ZN4Napi7details12CallbackDataIPFNS_6StringERKNS_12CallbackInfoEES2_E7WrapperEP10napi_env__P20napi_callback_info__]+0x7d): undefined reference to `napi_get_cb_info'
test.cc:(.text._ZN4Napi7details12CallbackDataIPFNS_6StringERKNS_12CallbackInfoEES2_E7WrapperEP10napi_env__P20napi_callback_info__[_ZN4Napi7details12CallbackDataIPFNS_6StringERKNS_12CallbackInfoEES2_E7WrapperEP10napi_env__P20napi_callback_info__]+0xce): undefined reference to `napi_get_cb_info'
Release/obj.target/xmljs/test.o: In function `_register_xmljs':
test.cc:(.text.startup+0xd): undefined reference to `napi_module_register'
collect2: error: ld returned 1 exit status
xmljs.target.mk:152: recipe for target 'Release/obj.target/xmljs.node' failed
make: *** [Release/obj.target/xmljs.node] Error 1
make: Leaving directory '/home/jstefani/Documents/github/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jstefani/.nvm/versions/node/v10.16.0/lib/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/home/jstefani/.nvm/versions/node/v10.16.0/bin/node" "/home/jstefani/.nvm/versions/node/v10.16.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/jstefani/Documents/github/libxmljs
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
```

**Comment by NickNaso** [comment]
Hi @jonathansensus,
I downloaded  `libxmljs` I modified the `binding.gyp` like reported below:
```gyp
{
  'targets': [
    {
      'target_name': 'xmljs',
      'product_extension': 'node',
      'type': 'shared_library',
      'include_dirs': [
        'vendor/libxml/include',
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      'dependencies': [
        "<!(node -p \"require('node-addon-api').gyp\")"
      ],
      'cflags': [ '-Wall' ],
      'cflags!': [ '-fno-exceptions' ],
      'cflags_cc!': [ '-fno-exceptions' ],
      'sources': [
        #'src/libxmljs.cc',
        #'src/xml_attribute.cc',
        #'src/xml_document.cc',
        #'src/xml_element.cc',
        #'src/xml_comment.cc',
        #'src/xml_namespace.cc',
        #'src/xml_node.cc',
        #'src/xml_sax_parser.cc',
        #'src/xml_syntax_error.cc',
        #'src/xml_text.cc',
        #'src/xml_pi.cc',
        #'src/xml_xpath_context.cc',
        'src/test.cc',
        'vendor/libxml/buf.c',
        'vendor/libxml/catalog.c',
        'vendor/libxml/chvalid.c',
        'vendor/libxml/dict.c',
        'vendor/libxml/encoding.c',
        'vendor/libxml/entities.c',
        'vendor/libxml/error.c',
        'vendor/libxml/globals.c',
        'vendor/libxml/hash.c',
        'vendor/libxml/HTMLparser.c',
        'vendor/libxml/HTMLtree.c',
        'vendor/libxml/legacy.c',
        'vendor/libxml/list.c',
        'vendor/libxml/parser.c',
        'vendor/libxml/parserInternals.c',
        'vendor/libxml/pattern.c',
        'vendor/libxml/relaxng.c',
        'vendor/libxml/SAX2.c',
        'vendor/libxml/SAX.c',
        'vendor/libxml/tree.c',
        'vendor/libxml/threads.c',
        'vendor/libxml/uri.c',
        'vendor/libxml/valid.c',
        'vendor/libxml/xinclude.c',
        'vendor/libxml/xlink.c',
        'vendor/libxml/xmlIO.c',
        'vendor/libxml/xmlmemory.c',
        'vendor/libxml/xmlmodule.c',
        'vendor/libxml/xmlreader.c',
        'vendor/libxml/xmlregexp.c',
        'vendor/libxml/xmlsave.c',
        'vendor/libxml/xmlschemas.c',
        'vendor/libxml/xmlschemastypes.c',
        'vendor/libxml/xmlstring.c',
        'vendor/libxml/xmlunicode.c',
        'vendor/libxml/xmlwriter.c',
        'vendor/libxml/xpath.c',
        'vendor/libxml/xpointer.c'
      ],
      'conditions': [
        ['OS=="mac"', {
          # node-gyp 2.x doesn't add this anymore
          # https://github.com/TooTallNate/node-gyp/pull/612
          'xcode_settings': {
            'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
            'CLANG_CXX_LIBRARY': 'libc++',
            'MACOSX_DEPLOYMENT_TARGET': '10.7',
            'CLANG_CXX_LANGUAGE_STANDARD': 'c++11',
            'OTHER_LDFLAGS': [
              '-undefined dynamic_lookup',
              '-Wall'
            ],
          },
        }]
      ]
    }
  ]
}
```
In the `test.cc` file I put the following code:

```cpp
#include <napi.h>

Napi::String Method(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  return Napi::String::New(env, "world");
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "hello"),
              Napi::Function::New(env, Method));
  return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, Init)
```
Then I builded the add-on using the following command:

```bash
node-gyp rebuild
```
All seems work fine.  Could this help you?

**Comment by jonathansensus** [comment]
This does help. It was able to finish the build. Thank you @NickNaso
