### ISSUE TITLE
IsExceptionPending() fails after multiple calls

### ISSUE THREAD

**Issue by bmacnaughton** [nodejs/node-addon-api#648]
I've written some code that invokes a JavaScript callback from within C++ callbacks for GC (using `v8::Isolate::GetCurrent()->AddGCPrologueCallback()` and `AddGCEpilogueCallback()`). I had an error in the JavaScript callback so added code to check for a pending exception.

```
  if (cbAfter != nullptr) {
    Napi::Env env = cbAfter.Env();
    Napi::Value jstype = Napi::Number::New(env, type);
    Napi::Value jsflags = Napi::Number::New(env, flags);
    Napi::Value deltaTime = Napi::Number::New(env, delta_time);
    Napi::Value gcCount = Napi::Number::New(env, 1);
    Napi::Value error = Napi::Boolean::New(env, begin.out_of_order_count != raw.out_of_order_count);
    std::vector<napi_value> args = {jstype, jsflags, deltaTime, gcCount, error};

    cbAfter.Call(args);
    if (env.IsExceptionPending()) {
      Napi::Error e = env.GetAndClearPendingException();
      std::cerr << "after exception:" + e.Message() + "\n";
      //e.ThrowAsJavaScriptException();
    }
  }
```

The JavaScript handler is just for testing right now:
```
function after (type, flags, deltaTime, gcCount, error) {
  console.log('<<', ...arguments)
  console.log('type', type, 'error', error, 'et', deltaTime, 'cet', cumET);
  throw new Error('oops');
  cumET += deltaTime;
}
```
The problem is that `IsExceptionPending()` works once or twice but fails after that. 
```
>> 1 0 false
<< 1 0 5568138 1 false
type 1 error false et 5568138 cet 0
after exception:oops
>> 1 0 false
<< 1 0 259660 1 false
type 1 error false et 259660 cet 0
after exception:oops
>> 1 0 false
<< 1 0 120651 1 false
type 1 error false et 120651 cet 0


#
# Fatal error in , line 0
# Missing deoptimization information for OptimizedFrame::Summarize.
#
#
#
#FailureMessage Object: 0x7fffa68ed820Illegal instruction (core dumped)
```

This is the first time I've tried using `IsExceptionPending()` so I might be doing something very basic wrong. In this case, I control the callback so it's possible for me to prevent the problem (indeed it was a typo that got me going down this path to begin with). But I'd like to be able to handle this case for future reference.

binding.gyp
```
{
  "targets": [
    {
      "target_name": "gc-watcher",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [ "gc-watcher.cc" ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
    }
  ]
}
```

**Comment by bmacnaughton** [comment]
catching the exception in JavaScript doesn't prevent the problem. if I change the `after` function to:
```
function after (type, flags, deltaTime, gcCount, error) {
  console.log('<<', ...arguments)
  console.log('type', type, 'error', error, 'et', deltaTime, 'cet', cumET);
  try {
    throw new Error('oops');
  } catch (e) {
    console.log('caught it');
  }
  cumET += deltaTime;
}
```

the resulting output is:
```
>> 1 0 false
<< 1 0 5504783 1 false
type 1 error false et 5504783 cet 0
caught it
>> 1 0 false
<< 1 0 216130 1 false
type 1 error false et 216130 cet 5504783
caught it
>> 1 0 false
<< 1 0 146302 1 false
type 1 error false et 146302 cet 5720913


#
# Fatal error in , line 0
# Missing deoptimization information for OptimizedFrame::Summarize.
#
#
#
#FailureMessage Object: 0x7ffd5db99580Illegal instruction (core dumped)
```

**Comment by mhdawson** [comment]
Is this on master with the latest node-addon-api? The nightly tests started failing a few days ago and we need to investigate that. If you are master and latest node-addon-api it could be related.

**Comment by bmacnaughton** [comment]
sorry i left off details
{
  node: '12.13.0',
  v8: '7.7.299.13-node.12',
  uv: '1.32.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '5',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}

**Comment by bmacnaughton** [comment]
all the code to demonstrate the problem handling errors in the javascript callback:  https://github.com/bmacnaughton/gc-watcher

`git clone https://github.com/bmacnaughton/gc-watcher`
`cd gc-watcher && npm install`
`node gc-watcher.js error`

to run without errors but with callbacks:
`node gc-watcher.js callbacks`

and without callbacks at all:
`node gc-watcher.js`

there are only two dependencies, `bindings` and `node-addon-api`.

**Comment by bmacnaughton** [comment]
the stack trace from loading the addon debug and running node with gdb:

```
# Missing deoptimization information for OptimizedFrame::Summarize.
#
#
#
#FailureMessage Object: 0x7fffffffb6b0
Thread 1 "node" received signal SIGILL, Illegal instruction.
0x000000000197ae59 in v8::base::OS::Abort() ()
(gdb) backtrace
#0  0x000000000197ae59 in v8::base::OS::Abort() ()
#1  0x0000000001976506 in V8_Fatal(char const*, ...) ()
#2  0x0000000000c86ab5 in v8::internal::OptimizedFrame::Summarize(std::vector<v8::internal::FrameSummary, std::allocator<v8::internal::FrameSummary> >*) const
    ()
#3  0x0000000000c8b3f7 in v8::internal::(anonymous namespace)::CaptureStackTrace(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::(anonymous namespace)::CaptureStackTraceOptions) ()
#4  0x0000000000c8bb43 in v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) ()
#5  0x0000000000c9d170 in v8::internal::ErrorUtils::Construct(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>, v8::internal::ErrorUtils::StackTraceCollection) ()
#6  0x0000000000bd2545 in v8::internal::Builtin_ErrorConstructor(int, unsigned long*, v8::internal::Isolate*) ()
#7  0x00000000013726d9 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit () at ../../deps/v8/../../deps/v8/src/builtins/base.tq:3028
#8  0x00000000012ee5ba in Builtins_JSBuiltinsConstructStub ()
    at ../../deps/v8/../../deps/v8/src/builtins/base.tq:325
#9  0x00003ea54ad416e1 in ?? ()
---Type <return> to continue, or q <return> to quit---
#10 0x00003ea54ad416e1 in ?? ()
#11 0x0000000600000000 in ?? ()
#12 0x0000067cdb480589 in ?? ()
#13 0x00003c1dec553a61 in ?? ()
#14 0x0000067cdb480589 in ?? ()
#15 0x0000000100000000 in ?? ()
#16 0x0000002806abfeb9 in ?? ()
#17 0x0000000000000024 in ?? ()
#18 0x00007fffffffc3a0 in ?? ()
#19 0x00000000013d2d80 in Builtins_ConstructHandler ()
    at ../../deps/v8/../../deps/v8/src/builtins/base.tq:300
Backtrace stopped: frame did not save the PC
```

**Comment by bmacnaughton** [comment]
i am (likely) causing allocations in my callback. i'm going to fix that to see it is causes this issue.

**Comment by bmacnaughton** [comment]
my problem is that i am creating objects in the callback. i will work around that.

**Comment by bmacnaughton** [comment]
rereading the v8 documentation - creating objects and even triggering a garbage collection should not cause this problem. so maybe there is a separate problem here. i'll try to isolate before either reopening or submitting a new issue.
