### ISSUE TITLE
Make callback in Object::AddFinalizer movable

### ISSUE THREAD

**Issue by ikokostya** [nodejs/node-addon-api#734]
**First problem**

Suppose I want to pass some data to finalization callback. To achieve this I need to use heap allocated data, because [`AddFinalizer`](https://github.com/nodejs/node-addon-api/blob/master/doc/object.md#addfinalizer) takes data by pointer:

```cpp
#include <napi.h>

void Test(const Napi::CallbackInfo& info) {
  auto obj_ref = new Napi::ObjectReference{};
  *obj_ref = Napi::Persistent(Napi::Object::New(info.Env()));

  info[0].As<Napi::Object>().AddFinalizer(
      [](Napi::Env env, Napi::ObjectReference* ref) {
        // Do something with ref.
        delete ref;
      },
      obj_ref);
}

Napi::Object InitAll(Napi::Env env, Napi::Object exports) {
  exports.Set("test", Napi::Function::New(env, Test));
  return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, InitAll)
```

The example above has problem. If `AddFinalizer` fails https://github.com/nodejs/node-addon-api/blob/9c9accfbbe8c27f969d569f78758a8c47837321b/napi-inl.h#L1236-L1239 we got memory leak, because reference `obj_ref` will not be deleted. If `NAPI_CPP_EXCEPTIONS` macro is defined, we can catch `Napi::Error`:

```diff
@@ -4,12 +4,17 @@ void Test(const Napi::CallbackInfo& info) {
   auto obj_ref = new Napi::ObjectReference{};
   *obj_ref = Napi::Persistent(Napi::Object::New(info.Env()));
 
-  info[0].As<Napi::Object>().AddFinalizer(
-      [](Napi::Env env, Napi::ObjectReference* ref) {
-        // Do something with ref.
-        delete ref;
-      },
-      obj_ref);
+  try {
+    info[0].As<Napi::Object>().AddFinalizer(
+        [](Napi::Env env, Napi::ObjectReference* ref) {
+          // Do something with ref.
+          delete ref;
+        },
+        obj_ref);
+  } catch (const Napi::Error& err) {
+    delete obj_ref;
+    throw;
+  }
 }
 
 Napi::Object InitAll(Napi::Env env, Napi::Object exports) {
```

But if `NAPI_CPP_EXCEPTIONS` macro is not defined, there is no way to detect on C++ side that `AddFinalizer` is failed.

***

**Second problem**

I want to use smart pointer for moving ownership to finalization callback:

```cpp
#include <napi.h>

void Test(const Napi::CallbackInfo& info) {
  auto obj_ref = Napi::Persistent(Napi::Object::New(info.Env()));

  info[0].As<Napi::Object>().AddFinalizer(
      [ref = std::move(obj_ref)](Napi::Env env, int* dummy_data) {
        // Do something with ref.
      },
      static_cast<int*>(nullptr));
}

Napi::Object InitAll(Napi::Env env, Napi::Object exports) {
  exports.Set("test", Napi::Function::New(env, Test));
  return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, InitAll)
```  

Unfortunately this produces compilation error (see below), because internally `AddFinalizer` tries to copy provided callback. Also, in this case `data` parameter of `AddFinalizer` method is redundant, and therefore, can be optional.

<details>
<summary>Compilation error</summary>

```
node_modules/.bin/node-gyp build -j max
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.14.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Debug', '-C', 'build', '--jobs', 8 ]
make[1]: Entering directory '/home/kostya/code/napi-finalizer-test/build'
  CXX(target) Debug/obj.target/test/src/binding.o
In file included from /home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi.h:2426,
                 from ../src/binding.cc:1:
/home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi-inl.h: In instantiation of ‘void Napi::Object::AddFinalizer(Finalizer, T*) [with Finalizer = Test(const Napi::CallbackInfo&)::<lambda(Napi::Env, int*)>; T = int]’:
../src/binding.cc:10:33:   required from here
/home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi-inl.h:1229:5: error: use of deleted function ‘Test(const Napi::CallbackInfo&)::<lambda(Napi::Env, int*)>::<lambda>(const Test(const Napi::CallbackInfo&)::<lambda(Napi::Env, int*)>&)’
 1229 |     new details::FinalizeData<T, Finalizer>({ finalizeCallback, nullptr });
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:7:32: note: ‘Test(const Napi::CallbackInfo&)::<lambda(Napi::Env, int*)>::<lambda>(const Test(const Napi::CallbackInfo&)::<lambda(Napi::Env, int*)>&)’ is implicitly deleted because the default definition would be ill-formed:
    7 |       [ref = std::move(obj_ref)](Napi::Env env, int* dummy_data) {
      |                                ^
../src/binding.cc:7:32: error: ‘Napi::ObjectReference::ObjectReference(const Napi::ObjectReference&)’ is protected within this context
In file included from /home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi.h:2426,
                 from ../src/binding.cc:1:
/home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi-inl.h:2512:8: note: declared protected here
 2512 | inline ObjectReference::ObjectReference(const ObjectReference& other)
      |        ^~~~~~~~~~~~~~~
In file included from /home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi.h:2426,
                 from ../src/binding.cc:1:
/home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi-inl.h:123:8: warning: ‘static void Napi::details::FinalizeData<T, Finalizer, Hint>::Wrapper(napi_env, void*, void*) [with T = int; Finalizer = Test(const Napi::CallbackInfo&)::<lambda(Napi::Env, int*)>; Hint = void]’ used but never defined
  123 |   void Wrapper(napi_env env, void* data, void* finalizeHint) {
      |        ^~~~~~~
/home/kostya/code/napi-finalizer-test/node_modules/node-addon-api/napi-inl.h:27:27: warning: ‘napi_status Napi::details::AttachData(napi_env, napi_value, FreeType*, napi_finalize, void*) [with FreeType = int]’ used but never defined
   27 | static inline napi_status AttachData(napi_env env,
      |                           ^~~~~~~~~~
make[1]: *** [test.target.mk:117: Debug/obj.target/test/src/binding.o] Error 1
make[1]: Leaving directory '/home/kostya/code/napi-finalizer-test/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/kostya/code/napi-finalizer-test/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.0-29-generic
gyp ERR! command "/home/kostya/.nvm/versions/node/v12.14.0/bin/node" "/home/kostya/code/napi-finalizer-test/node_modules/.bin/node-gyp" "build" "-j" "max"
gyp ERR! cwd /home/kostya/code/napi-finalizer-test
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
```
</details>

**Comment by mhdawson** [comment]
For

> But if NAPI_CPP_EXCEPTIONS macro is not defined, there is no way to detect on C++ side that AddFinalizer is failed.

I think you should be able to call info.Env().IsExceptionPending()
